type: server
config:
  server:
    domains:
      - example.org
      - example.net
  metrics:
    enabled: true
replicaCount: 1
ingress:
  enabled: true
  hosts:
    - host: cloudflare-dyndns.example.org
      paths:
        - path: /
          pathType: Prefix
